language: android

node_js:
  - 6.9.1

notifications:
  email: false

sudo: true

branches:
  only:
  - master
  
android:
  components:
    - build-tools-25.0.2
    
install:
  - sudo apt-get install npm
  - sudo apt-get install node
  - cd rotaract3220
  - sudo npm install
  - sudo npm cache clean
  #- sudo npm install -g cordova
  #- echo y | android update sdk -u --filter android-22,android-23
  - ls
 #- node -v
  - which node
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  # cordova build
  
script:
  - npm node -v
  - sudo npm install -g cordova
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  - sudo cordova prepare
  - sudo cordova build android --release
  - sudo npm install -g yarn
  - yarn install -g cordova
  - sudo cordova prepare
  - sudo cordova build android --release
  
release:
- exit 0
