language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: true

branches:
  only:
  - master

install:
  - cd rotaract3220
  - sudo apt-get install npm
  - sudo npm install
  - sudo npm cache clean
  - sudo npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23
  - ls
  - cordova platform remove android
  - cordova platform add android
  - cordova prepare
  - cordova build android --release -- --ant
  
script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
- exit 0
