language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: true

branches:
  only:
  - master
  
android:
  components:
    - build-tools-25.0.2
    
install:
  - sudo apt-get install npm
  - cd rotaract3220
  - sudo npm install
  - sudo npm cache clean
  - sudo npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23
  - ls
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - cordova build
  
script:
  - cordova prepare
  - cordova build android --release
  
release:
- exit 0
