language: android

node_js:
  - 5.5

notifications:
  email: false

sudo: true

branches:
  only:
  - master
  
android:
  components:
    - build-tools-25.0.2

install:
  - cd rotaract3220
  - sudo apt-get install npm
  - sudo npm install
  - sudo npm cache clean
  - sudo npm install -g cordova
  - echo y | android update sdk -u --filter android-22,android-23
  - ls
  - sudo ln -s /usr/bin/nodejs /usr/bin/node
  - cordova
  - cordova platform remove android
  - cordova platform add android
  
script:
  - cordova prepare
  - cordova build android --release -- --ant
  
release:
- exit 0
