#lets see how this works
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      install:
        - brew install npm
        - brew install node
        - cd rotaract3220
        - sudo npm install
        - sudo npm cache clean
        - sudo npm install -g cordova
        - sudo npm cache clean -f
        - sudo npm install -g n
        - sudo n stable
        #- cordova build
      script:
        - echo y | sudo cordova platform add ios --no-insight
        - sudo cordova prepare --no-insight
        - sudo cordova build ios --release --no-insight
notifications:
  email: false
 
