#lets see how this works | creates to build jobs
matrix:
  include:
    #android app 
    - language: android
      jdk: oraclejdk8
      node_js:
        - 6.9.1
      sudo: true
      branches:
        only:
          - master
      android:
        components:
          - build-tools-26.0.2
      install:
        - sudo apt-get install npm
        - sudo apt-get install node
        - cd rotaract3220
        - sudo npm install
        - sudo npm cache clean
        - sudo npm install -g cordova
        - echo y | android update sdk -u --filter android-22,android-26
        - sudo npm cache clean -f
        - sudo npm install -g n
        - sudo n stable
        - cordova build
      script:
        - sudo cordova prepare
        - sudo cordova build android --release
      release:
        - exit 0
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        on:
          branch: master
  
    #ios deployment test | works but sandboxed debug file cannot be used
    - language: objective-c
      os: osx
      osx_image: xcode9.2
      install:
        - brew install npm
        - brew install node
        - cd rotaract3220
        - sudo npm install
        - sudo npm cache clean
        - sudo npm install -g cordova
        - sudo npm cache clean -f
        - sudo npm install -g n
        - sudo n stable
        #- cordova build
      script:
        - echo y | sudo cordova platform add ios --no-insight
        - sudo cordova build ios --release --no-insight
      release:
        - exit 0
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
        keep-history: true
        on:
          branch: master
notifications:
  email: false
 
